configFiles:
  Debug: Modules/xcconfigs/Project-Debug.xcconfig
  Release: Modules/xcconfigs/Project-Release.xcconfig
fileGroups:
- Modules/App
- Modules/Maverick-MacOS/
include:
- Modules/App/app.yml
- Modules/Maverick-MacOS/Maverick-MacOS.yml
name: Maverick
